@extends('layouts.app')

@section('content_body')
@if (Auth::guard('users')->check())<!-- this code is active if the person login is user -->
    <router-view :data_user="{{Auth::guard('users')->user()}}" :mails="{{DB::table('sender')->get()}}" :maintenance_db="{{DB::table('maintenance_db')->get()}}" :id_num_pay="{{ collect(DB::table('h_pay_part_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_add="{{ collect(DB::table('h_add_part_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_return_add="{{ collect(DB::table('h_addreturn_report_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_check_report="{{ collect(DB::table('h_chack_report_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_order_pay1="{{ collect(DB::table('h_payrequest_report_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_order_pay2="{{ collect(DB::table('h_payrequest_normal_report_db')->get('id_num'))->max()->id_num??"0" }}" :depart="{{ DB::table('department')->get() }}" ></router-view>
@endif
@if (Auth::guard('admins')->check())<!-- this code is active if the person login is admin -->
    <router-view :data_user="{{Auth::guard('admins')->user()}}" :mails="{{DB::table('sender')->get()}}" :maintenance_db="{{DB::table('maintenance_db')->get()}}" :id_num_pay="{{ collect(DB::table('h_pay_part_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_add="{{ collect(DB::table('h_add_part_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_return_add="{{ collect(DB::table('h_addreturn_report_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_check_report="{{ collect(DB::table('h_chack_report_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_order_pay1="{{ collect(DB::table('h_payrequest_report_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_order_pay2="{{ collect(DB::table('h_payrequest_normal_report_db')->get('id_num'))->max()->id_num??"0" }}" :depart="{{DB::table('department')->get() }}" ></router-view>
@endif
@if (Auth::guard('top_admins')->check())<!-- this code is active if the person login is top_admin -->
    <router-view :data_user="{{Auth::guard('top_admins')->user()}}" :mails="{{DB::table('sender')->get()}}" :maintenance_db="{{DB::table('maintenance_db')->get()}}" :id_num_pay="{{ collect(DB::table('h_pay_part_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_add="{{ collect(DB::table('h_add_part_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_return_add="{{ collect(DB::table('h_addreturn_report_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_check_report="{{ collect(DB::table('h_chack_report_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_order_pay1="{{ collect(DB::table('h_payrequest_report_db')->get('id_num'))->max()->id_num??"0" }}" :id_num_order_pay2="{{ collect(DB::table('h_payrequest_normal_report_db')->get('id_num'))->max()->id_num??"0"}}" :depart="{{DB::table('department')->get() }}" ></router-view>
@endif
@endsection
